"""empty message

Revision ID: 076ff5df75df
Revises: 
Create Date: 2018-10-28 15:35:26.042931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076ff5df75df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_schedule_name'), 'schedule', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_name'), table_name='schedule')
    op.drop_column('schedule', 'name')
    # ### end Alembic commands ###
