"""empty message

Revision ID: 5cb24e5497a3
Revises: 
Create Date: 2018-11-15 21:53:50.193437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb24e5497a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('hrs_to_work', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_schedule_hrs_to_work'), 'schedule', ['hrs_to_work'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_hrs_to_work'), table_name='schedule')
    op.drop_column('schedule', 'hrs_to_work')
    # ### end Alembic commands ###
