"""empty message

Revision ID: 7ef48679d4a6
Revises: c47a6edc81c0
Create Date: 2018-10-21 19:24:13.971790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef48679d4a6'
down_revision = 'c47a6edc81c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('workplace', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'workplace')
    # ### end Alembic commands ###
