"""empty message

Revision ID: c47a6edc81c0
Revises: 
Create Date: 2018-10-21 16:48:44.259385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47a6edc81c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('begin_hour', sa.Integer(), nullable=True))
    op.add_column('schedule', sa.Column('end_hour', sa.Integer(), nullable=True))
    op.add_column('schedule', sa.Column('event', sa.String(), nullable=True))
    op.add_column('schedule', sa.Column('hours_sum', sa.Integer(), nullable=True))
    op.add_column('schedule', sa.Column('worker', sa.String(), nullable=True))
    op.create_index(op.f('ix_schedule_date'), 'schedule', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_date'), table_name='schedule')
    op.drop_column('schedule', 'worker')
    op.drop_column('schedule', 'hours_sum')
    op.drop_column('schedule', 'event')
    op.drop_column('schedule', 'end_hour')
    op.drop_column('schedule', 'begin_hour')
    # ### end Alembic commands ###
