"""empty message

Revision ID: c6166da2b352
Revises: 7ef48679d4a6
Create Date: 2018-10-27 23:16:19.697886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6166da2b352'
down_revision = '7ef48679d4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schedule_date', table_name='schedule')
    op.drop_table('schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('begin_hour', sa.INTEGER(), nullable=True),
    sa.Column('end_hour', sa.INTEGER(), nullable=True),
    sa.Column('event', sa.VARCHAR(), nullable=True),
    sa.Column('hours_sum', sa.INTEGER(), nullable=True),
    sa.Column('worker', sa.VARCHAR(), nullable=True),
    sa.Column('workplace', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedule_date', 'schedule', ['date'], unique=False)
    # ### end Alembic commands ###
