"""empty message

Revision ID: fab5a4e707c4
Revises: 
Create Date: 2019-03-13 21:38:00.244578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab5a4e707c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begin', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_period_begin'), 'billing_period', ['begin'], unique=False)
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('workplace', sa.String(), nullable=True),
    sa.Column('hrs_to_work', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('billing_period', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_accepted'), 'schedule', ['accepted'], unique=False)
    op.create_index(op.f('ix_schedule_billing_period'), 'schedule', ['billing_period'], unique=False)
    op.create_index(op.f('ix_schedule_hrs_to_work'), 'schedule', ['hrs_to_work'], unique=False)
    op.create_index(op.f('ix_schedule_id'), 'schedule', ['id'], unique=True)
    op.create_index(op.f('ix_schedule_name'), 'schedule', ['name'], unique=False)
    op.create_index(op.f('ix_schedule_timestamp'), 'schedule', ['timestamp'], unique=False)
    op.create_index(op.f('ix_schedule_version'), 'schedule', ['version'], unique=False)
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_shopname'), 'shop', ['shopname'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('access_level', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_access_level'), 'user', ['access_level'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('guidelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workplace', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('no_of_workers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workplace'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guidelines_day'), 'guidelines', ['day'], unique=False)
    op.create_index(op.f('ix_guidelines_id'), 'guidelines', ['id'], unique=True)
    op.create_index(op.f('ix_guidelines_month'), 'guidelines', ['month'], unique=False)
    op.create_index(op.f('ix_guidelines_no_of_workers'), 'guidelines', ['no_of_workers'], unique=False)
    op.create_index(op.f('ix_guidelines_year'), 'guidelines', ['year'], unique=False)
    op.create_table('personal_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('worker', sa.String(), nullable=True),
    sa.Column('begin_hour', sa.Integer(), nullable=True),
    sa.Column('end_hour', sa.Integer(), nullable=True),
    sa.Column('hours_sum', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('workplace', sa.String(), nullable=True),
    sa.Column('billing_period', sa.Integer(), nullable=True),
    sa.Column('billing_week', sa.Integer(), nullable=True),
    sa.Column('includes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['includes_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_schedule_billing_period'), 'personal_schedule', ['billing_period'], unique=False)
    op.create_index(op.f('ix_personal_schedule_billing_week'), 'personal_schedule', ['billing_week'], unique=False)
    op.create_index(op.f('ix_personal_schedule_date'), 'personal_schedule', ['date'], unique=False)
    op.create_index(op.f('ix_personal_schedule_id'), 'personal_schedule', ['id'], unique=True)
    op.create_table('workplaces',
    sa.Column('worker', sa.Integer(), nullable=True),
    sa.Column('workplace', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['worker'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workplace'], ['shop.id'], )
    )
    op.execute('INSERT INTO "user" VALUES (1, "admin admin", "pbkdf2:sha256:50000$Fv8pGxVC$f13556c64ea24875a6a550a827d1e769d332bd58a4d996c561af581727ca333f", "0");')
    op.execute('INSERT INTO "user" VALUES (2, "Example worker", "pbkdf2:sha256:50000$Fv8pGxVC$f13556c64ea24875a6a550a827d1e769d332bd58a4d996c561af581727ca333f", "4");')
    op.execute('INSERT INTO "shop" VALUES (1, "Example Workplace");')
    op.execute('INSERT INTO "workplaces" VALUES (1, 1);')
    op.execute('INSERT INTO "workplaces" VALUES (2, 1);')
    op.execute('INSERT INTO "billing_period" VALUES (1, "2018-01-01 00:00:00.000000", 3);')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workplaces')
    op.drop_index(op.f('ix_personal_schedule_id'), table_name='personal_schedule')
    op.drop_index(op.f('ix_personal_schedule_date'), table_name='personal_schedule')
    op.drop_index(op.f('ix_personal_schedule_billing_week'), table_name='personal_schedule')
    op.drop_index(op.f('ix_personal_schedule_billing_period'), table_name='personal_schedule')
    op.drop_table('personal_schedule')
    op.drop_index(op.f('ix_guidelines_year'), table_name='guidelines')
    op.drop_index(op.f('ix_guidelines_no_of_workers'), table_name='guidelines')
    op.drop_index(op.f('ix_guidelines_month'), table_name='guidelines')
    op.drop_index(op.f('ix_guidelines_id'), table_name='guidelines')
    op.drop_index(op.f('ix_guidelines_day'), table_name='guidelines')
    op.drop_table('guidelines')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_access_level'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_shop_shopname'), table_name='shop')
    op.drop_table('shop')
    op.drop_index(op.f('ix_schedule_version'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_timestamp'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_name'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_hrs_to_work'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_billing_period'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_accepted'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_billing_period_begin'), table_name='billing_period')
    op.drop_table('billing_period')
    # ### end Alembic commands ###
